### ISSUE TITLE
FAQ link not working

### ISSUE THREAD

**Issue by trivalik** [MicrosoftDocs/windows-iotcore-docs#1181]
The FAQ link https://developer.microsoft.com/en-us/windows/iot/faqs is not working anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91b486ae-25c4-c070-ecb1-049bea64903e
* Version Independent ID: 21719e23-85b0-e246-aaca-e9a5254e88d3
* Content: [Use DISM to flash Windows 10 IoT Core - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/connect-your-device/dism#feedback)
* Content Source: [windows-iotcore/connect-your-device/DISM.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/connect-your-device/DISM.md)
* Product: **windows-iot**
* Technology: **iot**
* GitHub Login: @bfjelds
* Microsoft Alias: **bfjelds**

**Comment by bfjelds** [comment]
Thank you for bringing this to our attention … we'll work to fix that!  In the meantime, here is the content that used to be found in the "How do I remove Windows 10 IoT Core from my SD card" section of the FAQ:

After you've flashed the Windows 10 IoT Core image to your 
SD card, the reported size of the card will drop to 67.3MB. 
	
In order to restore the card back for general use, you'll 
need to run a series commands in an elevated command 
prompt (Simply reformatting the card alone won't work):

        diskpart
        list disk (This command lists the drives you have connected to your computer. Take note of the disk number of your SD card)
        select disk <number> (Replace <number> with the disk number of your SD card from the previous step
        clean
        create partition primary
        format fs=ntfs quick
        exit

Your SD card is now ready for general purpose use again.
