### ISSUE TITLE
Insider builds not shown under "OS Build"

### ISSUE THREAD

**Issue by NathanielJS1541** [MicrosoftDocs/windows-iotcore-docs#1290]
This is a follow up to issue #1274. I am pleased to say that the latest update of the IoT Core Dashboard (Mine updated to 1.0.1905.6001) has fixed many of the UI issues I was experiencing. The sign in works much better and I no longer get the "Failed to get insider build" message.  
However, when I sign in I can no longer see any insider builds in the "OS Build" dropdown (screenshot attached). The only build I get listed is 17763 (And I believe the current insider build is 17744?). I'm not sure if this is intentional so I thought I'd open an issue for it.  
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/33491104/57517142-16287f80-730e-11e9-8843-34b6622d058e.PNG">
As a side note if you sign out and back in again you get this error when trying to sign back in. Should I open a separate issue for this?
<img width="960" alt="Capture2" src="https://user-images.githubusercontent.com/33491104/57517143-16287f80-730e-11e9-82f3-94c373a8c005.PNG">

**Comment by saraclay** [comment]
@NathanielJS1541, thank you again for the thorough issue. Yes - only 17763 is shown because that's the most updated release. We've suspended Insider releases for now as we're on our long-term servicing channel, but do expect Insider releases to be back sometime later in the year.

As for the issue you've noticed, we haven't seen that before, but that's probably because it's not a common scenario. If you could try to repro it once more, yes, a separate issue would be much appreciated, thank you.
