### ISSUE TITLE
Raspberry PI 3 Bluetooth driver problem

### ISSUE THREAD

**Issue by Parsakarami** [MicrosoftDocs/windows-iotcore-docs#675]
Is the Raspberry PI 3 Bluetooth driver problem solved on October 2018 version of windows?

In the previous version of windows IoT core on raspberry pi 3 (model B) the internal bluetooth adapter works for 20 to 30 minutes perfectly but after this period of time it completely will be out of access by others as advertiser of a ble service, an no phone can find it.

Is the problem solved?

**Comment by saraclay** [comment]
Hi @Parsakarami, our team is taking a look. Thanks!

**Comment by saraclay** [comment]
Hi @Parsakarami, so it seems that there have been a few others that have reported that the on-board Bluetooth driver on the Raspberry Pi board isn't reliable when handling a high rate of sensor updates or are long-time running. Because the hardware does not implement compatible firmware or hardware flow control, the speed is limited to ~115kbps. High speed BT is not recommended on RPi/IoT Core using the onboard on RPi3 BT hardware. Does this help?

**Comment by Parsakarami** [comment]
Hi and thanks @saraclay for your help, so is Microsoft going to resolve this issue? Or not? 
If yes does Microsoft has any ETA for this? 
If no does Microsoft resolve it in Raspberry Pi 3 B+ ?

Before answering my questions, thank you for the help you made.

**Comment by saraclay** [comment]
Hi @Parsakarami, this is unfortunately a known issue on the Raspberry Pi itself. So we do not recommend high speed bluetooth and this does not resolve for B+.
