### ISSUE TITLE
Need more docs about the audio!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-iotcore-docs#775]
There is no docs about the audio.
The "[Stereo Connector and Audio Routing on DragonBoard 410c Application Note](https://developer.qualcomm.com/download/db410c/stereo-connector-and-audio-routing-application-note.pdf)" is a good start for the hardware information but the configuration of the driver and software in the application note are just for the Linux and Android. So, I need more docs here about the audio.

For example:
1. The number of the render device will be supported by the Windows 10 IoT Core?
2. The number of the capture device will be supported by the Windows 10 IoT Core?
3. Which is the default render and capture device, and how to change between them programmatically?

Hi @saraclay, do your job is just to close my issues? #774
Can't set the volume of the Speaker! #749
No Headset Earphone render device! #744
Dragonboard 410c analog MIC input #727

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf4b39be-e0ef-9db7-d542-248e8d107471
* Version Independent ID: 2862e930-3f9f-c73f-cf57-1396ceeeadc0
* Content: [Dragonboard Pin Mappings - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/pinmappings/pinmappingsdb)
* Content Source: [windows-iotcore/learn-about-hardware/PinMappings/PinMappingsDB.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/learn-about-hardware/PinMappings/PinMappingsDB.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by saraclay** [comment]
Hi @moyanming - ok, the team thought that the Qualcomm documentation would help, that is why I closed it as suggested by the team. Thank you for opening another issues - let me see what I can find.

**Comment by saraclay** [comment]
@moyanming and @endyb66, 
Windows 10 IoT Core supports operating system features - when it comes to hardware and audio-related issues that are on the Qualcomm side of things, we cannot help. Please contact Qualcomm or work with a distributor for questions. You can find a list of our distributors here: http://wincom.blob.core.windows.net/documents/Windows_IoT_Distributor_Information.pdf 

The documentation issues channel is not the appropriate platform for hardware issues. The MSDN forums is our best destination for issues you're running into as this channel is staffed and constantly monitored. If you have documentation-related issues to address, please open an issue. Otherwise, I cannot help you.

The link to the MSDN forums is here: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT
